//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucksUniSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentID { get; set; }
        public string IncidentTitle { get; set; }
        public string IncidentLocation { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public string IncidentDescription { get; set; }
        public int CentreID { get; set; }
    
        public virtual Centre Centre { get; set; }
    }
}
